FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git ca-certificates
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.22.0


FROM alpine:3.20

RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/goose /usr/local/bin/goose

WORKDIR /migrations

ENTRYPOINT ["goose"]
CMD ["--help"]
